version: "3.7"

services:
  club_app: &app
    build:
      dockerfile: production.dockerfile
      context: .
    command: make docker-run-production
    container_name: club_app
    environment:
      - PYTHONUNBUFFERED=1
      - DEBUG=false
      - APP_HOST=https://phangan.me
      - POSTGRES_DB=vas3k_club
      - POSTGRES_USER=vas3k
      - POSTGRES_PASSWORD=vas3k
      - POSTGRES_HOST=postgres
      - REDIS_DB=0
      - REDIS_HOST=redis
    restart: always
    volumes:
      - ./frontend:/app/frontend/
      - ./gdpr/downloads:/app/gdpr/downloads
    depends_on:
      - postgres
      - redis
      - queue
    ports:
      - "127.0.0.1:8814:8814"

  queue:
    <<: *app
    command: make docker-run-queue
    container_name: club_queue
    depends_on:
      - postgres
      - redis
    ports: []

  bot:
    <<: *app
    command: make docker-run-bot
    container_name: club_bot
    depends_on:
      - club_app
      - postgres
      - redis
    ports:
      - "8816:8816"

  postgres:
    image: postgres:12
    container_name: club_postgres
    restart: always
    environment:
      POSTGRES_USER: vas3k
      POSTGRES_PASSWORD: vas3k
      POSTGRES_DB: vas3k_club
    volumes:
      - /var/www/pgdata:/var/lib/postgresql/data:rw
    ports:
      - "127.0.0.1:54333:5432"

  redis:
    image: redis:alpine
    container_name: club_redis
    restart: always
    environment:
      - ALLOW_EMPTY_PASSWORD=yes

  pepic:
    build: ../i.phangan.me
    container_name: pepic
    environment: # check out pepic/config/app.go for more env variables
      - BASE_URL=http://i.phangan.me/
      - STORAGE_DIR=/uploads
      - SECRET_CODE=w@tareyoulooking?
      - IMAGE_ORIGINAL_LENGTH=1400
      - MAX_UPLOAD_SIZE=100M
    volumes:
      - ../i.phangan.me/uploads:/uploads
    ports:
      - 8118:8118
    user: "0" # set your real uid (by default only root can read the uploaded files)
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    # command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    container_name: club_nginx
    restart: always
    tty: true
    ports:
      - 8000:80
      # - 80:80
      # - 443:443
    volumes:
      - ./:/var/www/phangan.me/
      - ./etc/nginx/vas3k.club.conf/:/etc/nginx/conf.d/vas3k.club.conf
      - ./etc/nginx/i.vas3k.club.conf/:/etc/nginx/conf.d/i.vas3k.club.conf
      - ./etc/certbot/conf:/etc/letsencrypt
      - ./etc/certbot/www:/var/www/certbot
    depends_on:
      - club_app
      - pepic

  certbot:
    image: certbot/certbot
    container_name: certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    volumes:
      - ./etc/certbot/conf:/etc/letsencrypt
      - ./etc/certbot/www:/var/www/certbot
